# Generated by Django 3.1.5 on 2022-04-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categorias', '0001_initial'),
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idmarca', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('utilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('precioventa', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('importeiva', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fechaultima', models.DateField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('control_stock', models.BooleanField(blank=True, null=True)),
                ('stock_detallado', models.BooleanField(blank=True, null=True)),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('idcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categorias.categorias')),
                ('idmarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.marca')),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.proveedores')),
            ],
        ),
    ]
